export default [
  {name : "Ghost of Tsushima" ,
   id: 'Ghost-of-Tsushima' ,
   img:'img/Ghost of Tsushima .PNG' ,
   Platform: "PS4",
   price : 200 ,
   num:0,
   Release_date:'June 26, 2020' ,
   information : "Sucker Punch hit us with quite the surprise when it first revealed Ghost of Tsushima out of the blue: a samurai-led tale of ancient Japan from the studio that brought you the Infamous and Sly Cooper series. You play a swordsman known as \"The Ghost,\" who's fighting for his life against the invading forces of the Mongol Empire. The story that unfolds is based on real historical events that kicked off in the year 1274. The latest trailer that debuted at the Game Awards 2019 not only gave us a release date, it also showed off some seriously slick combat and a variety of gorgeous vistas in \"the biggest game Sucker Punch has ever made by wide margin.\"  Prepare yourself for plenty of intense melee combat in a large, open-world take on feudal Japan."
 },
 {name : "Tell Me Why" ,
  id: "Tell-Me-Why" ,
  img:'img/Tell Me Why.PNG' ,
  Platform: "PC, Xbox One",
  price : 150 ,
  num:0,
  Release_date:' Summer 2020' ,
  information : "Dontnod's latest narrative adventure follows the story of reunited twins Alyson and Tyler Ronan who have a special bond. Described as an \"intimate thriller,\" the twins use their special bond to uncover the mysterious of a troubled - albeit loving - childhood. The game is set to explore the idea of memory and both twins are playable protagonists, which sounds very intriguing. As with past Dontnod games like Life is Strange, you'll be able to make choices that shape the twins' story.  Interestingly the story will unfold over three chapters that will all release in the summer, so you'll be able to experience the narrative journey from start to finish. "
 },
 {name : "Wasteland 3" ,
  id: "Wasteland-3" ,
  img:'img/Wasteland 3.PNG' ,
  Platform: "PS4, Xbox One, PC",
  price : 150  ,
  num:0,
  Release_date:'August 28, 2020' ,
  information : "Set in the post-apocalyptic frozen lands of Colorado, Wasteland 3 looks like a fantastic tactical RPG to tuck into with your pals. Available to play entirely solo or in co-op, the third entry in the Wasteland series is a story-driven experience where your choices will matter. Every decision you make can offer you new opportunities or close you off to them, as well as take you to new areas and lead you to different story arcs. This choice and variety makes it sound very replayable, and the setting is set to present you with some difficult moral choices as you decide how to lead in the frozen wastes. This is definitely one to watch, especially since InXhile has been working to evolve the series' turn-based combat, and will also include a new dialogue system and fully voice acted characters to add to the immersive RPG side of the experience."
},
{name : "Marvel's Avengers" ,
 id: "Marvel's-Avengers"  ,
 img:'img/Marvel\'s Avengers.PNG' ,
 Platform: "PC, Xbox One, PS4",
 price : 400 ,
 num:0,
 Release_date:'September 4, 2020' ,
 information : "With the voice acting talents of Laura Bailey, Troy Baker, Nolan North, Travis Willingham, and Jeff Schine, Crystal Dynamics has assembled an a stellar cast to from the team of Avengers. With a story that's entirely separate to the MCU, we'll be able to play as Captain America, Thor, Iron Man, Black Widow, and Hulk. After being blamed for the disaster in San Francisco, the heroes reassemble when the world comes under a new threat five years later. With four player co-op, Marvel's Avengers looks to be one heroic adventure. "
},
{name : "Cyberpunk 2077" ,
 id: "Cyberpunk-2077"  ,
 img:'img/Cyberpunk 2077.PNG' ,
 Platform: "PC, PS4, Xbox One",
 price : 400 ,
 num:0,
 Release_date:'September 17, 2020' ,
 information : "CD Projekt Red has given us some absolutely ravishing teases of Cyberpunk 2077 and its futuristic Night City, and until we get to play it for ourselves, we'll be poring over every trailer and screenshot in search of new details. As a customizable protagonist, you'll explore a dense metropolis from the first-person perspective - a departure for the studio that initially sent some Witcher fans in a tizzy. They'll get over it when they dive into Cyberpunk 2077's grungy world of high-tech weaponry and digital espionage."
},
{name : "Halo Infinite" ,
 id: "Halo-Infinite" ,
 img:'img/Halo Infinite.PNG' ,
 Platform: "PC, Xbox One, Xbox Project Scarlett",
 price : 100 ,
 num:0,
 Release_date:'Holiday 2020' ,
 information : "Make no mistake; 343 Industries' follow-up to 2015's Halo 5 is still a long way off, but it's definitely happening. Bearing a curious new sub-header and running on a brand new game engine known as Slipspace, the first Halo Infinite trailer almost seems to suggest that Master Chief's next adventure will have MMO qualities to it, or at least be more open-ended and sandbox-like in flavour. That instantly familiar shot of his armour also teases a potential technological downgrade for everyone's favourite Spartan, though plot details remain threadbare for now. MMO or otherwise, Halo: Infinite could just be the Halo comeback we've all been waiting for. "
},
{name : "Godfall" ,
 id:  "Godfall" ,
 img:'img/Godfall.PNG' ,
 Platform: "PS5, PC (Epic Games Store)",
 price : 150  ,
 num:0,
 Release_date:'Holiday 2020' ,
 information : "As one of the first games to be announced for Sony's next-gen console, Godfall is set to land on the PS5 at the tail end of the year. Developer Counterplay Games describes it as a loot-driven action RPG, with a focus on real-time melee combat. The new IP is set in a fantasy universe with \"heroic knights, arcane magic, and forbidden realms.\" The game can also be played in its entirety in co-op or solo as you so desire. We don't yet know much more about this looter-slasher, but the shiny action-packed trailer and the game's high fantasy setting is certainly attention-grabbing."
},
{name : "Luigi's Mansion 3" ,
 id: "Luigi's-Mansion-3" ,
 img:'img/Luigi\'s Mansion 3.PNG' ,
 Platform: "Next Level Games",
 price : 100  ,
 num:0,
 Release_date:'2019' ,
 information : " A spooky spectacular set in a haunted high-rise hotel, with the other brother vacuuming up ghosts and calling on his slimy alter-ego Gooigi to solve puzzles to try and rescue his friends.\n\nWhy should you play it? Unless you have a life-threatening allergy to fun, this is a Nintendo Switch essential. Even then, it's probably worth the risk. The Last Resort hotel is a masterpiece of delightful visuals and supernaturally satisfying puzzles, and every floor has a new theme. Point your Poltergust G-00 vacuum at anything and everything for secrets, puzzle-solving, and sheer destructive satisfaction, or summon green Gooigi for the company or to help with puzzles that need some creative thinking. It's the sort of A+ action-adventure you expect from a big Nintendo title, but no expense has been spared on making sure it's as charming and memorable as it is mechanically marvelous. Move over Mario, because Luigi is the real star of 2019. Rachel Weber"
},
{name : "Call of Duty: Modern Warfare" ,
 id: "Call-of-Duty:-Modern-Warfare" ,
 img:'img/Call of Duty.PNG' ,
 Platform: "PC, PS4, Xbox One",
 price : 160 ,
 num:0,
 Release_date:'2019' ,
 information : " What is it? A reboot of the 15-year-old franchise that's more complex and morally gray than its forerunners, powered by a brand-new engine that churns out breathtaking graphics\n\nWhy should you play it? This frenetic shooter pulls back from the massive military set pieces synonymous with its namesake in favor of tighter, occasionally claustrophobic campaign missions. These missions make you feel the weight and consequences of war far better than other Call of Duty games have, even if it occasionally teeters on the precipice of torture porn. It's the most beautiful game in the series by a landslide, with mo-cap that barely dips a toe in the uncanny valley and set pieces that are truly jaw-dropping. Play the eight-hour campaign on the edge of your seat before firing up the multiplayer search for several rounds of the best version of it yet – with top notch gunplay and myriad game types that suit whatever mood you may be in at the moment (fancy a massive Ground War, perhaps?). Alyssa Mercante"
},
{name : "The Outer Worlds" ,
   id:  "The-Outer-Worlds" ,
   img:'img/The Outer Worlds.PNG' ,
   Platform: "PS4, Xbox One, PC",
   price : 160 ,
   Release_date:'2019' ,
   num:0,
   information : " What is it? A space RPG set in a future ruled by megacorporations, filled with eccentric characters, alien species, and bacon-flavored tumors.\n\nWhy should you play it? It mixes the fun and frolics of running around deep space, accompanied by a gang of weirdos carrying big guns, with complex stories about corruption and colonization. On top of that, it manages to deliver on the big RPG promises about choice. You can straight-up murder anyone you meet, ditch your team members and play solo, or try and make it through the whole game with your charm skill points alone. The tone is always tongue-in-cheek but still manages to deliver some genuinely touching moments with characters, like your introverted engineer buddy Parvati. The story doesn't shy away from forcing you to make tough decisions, so you might want to light a relaxing candle before you start, but that will only makes you desperate to play it all over again as soon as you're done. "
},
{name : "Control" ,
   id: "Control" ,
   img:'img/Control.PNG' ,
   Platform: " PC, PS4, Xbox One",
   price : 260  ,
   Release_date:'2019' ,
   num:0,
   information : "What is it? A magic and guns third-person shooter set in the 'new weird' world of cursed everyday objects and mind-bending multi-dimensional entities. \n\nWhy should you play it? Games should be a journey, and that journey's always more fun if it keeps you guessing. From the moment you enter the Oldest House, it's unpredictable walls and cursed objects put you on the back foot with little in the way of recognizable footholds to guide you. Its mechanics are familiar, as you psychically hurl desks at enemies and polish them off with gunfire, but the shifting physical geometry and vaporous story that writhes under scrutiny, leaves you guessing at every turn. And, potentially, staring at the back of your own head. It riffs beautifully on 'new weird' mythology, which shifts familiar mythical and magical ideas on to everyday objects – building on its playable mix of powers and weapons with an amazing world of cursed fridges, spooky ashtrays, and world-altering Walkmans. It speaks volumes of Control's strange new setting that reading files to discover why it takes an entire government agency to contain a small rubber duck is almost as much fun as blowing stuff up. Leon Hurley"
},
]
